pub const ParseError = error{
    NotImplemented,
    UnexpectedToken,
    NotBinaryOp,
    NotBasicLit,
    OutOfMemory,
    NotUnaryOp,
    ExpectedRParen,
    ExpectedRBrace,
    ExpectedLBrace,
    ExpectedLParen,
    ExpectedIdentifier,
    ExpectedColon,
    ExpectedComma,
};
